Динамическое программирование (DP)

алгоритм Value Iteration для нахождения оптимальной политики в среде FrozenLake-v1

ценность состояния

Уравнение Беллмана

V(s) = max​ s′∑​ P(s′ | s, a) [R(s, a, s′) + γV(s′)]

In [1]:
import gymnasium as gym
import numpy as np

In [2]:
env = gym.make("FrozenLake-v1", is_slippery=False)
n_states = env.observation_space.n
n_actions = env.action_space.n

In [3]:
gamma = 0.99
theta = 1e-6  # criteria сходимости
V = np.zeros(n_states)

In [8]:
def one_step_lookahead(state, V): #однократный просмотр вглубь
    A = np.zeros(n_actions)
    for a in range(n_actions):
        for prob, next_state, reward, done in env.unwrapped.P[state][a]:
            A[a] += prob * (reward + gamma * V[next_state])
    return A

In [10]:
while True: # value iteration
    delta = 0
    for s in range(n_states):
        A = one_step_lookahead(s, V)
        best_action_value = np.max(A)
        delta = max(delta, abs(best_action_value - V[s]))
        V[s] = best_action_value
    if delta < theta:
        break

policy = np.zeros(n_states, dtype=int) #оптимальная политика
for s in range(n_states):
    A = one_step_lookahead(s, V)
    policy[s] = np.argmax(A)

print("оптимальное V:\n", V.reshape(4,4))
print("оптимальная политика:\n", policy.reshape(4,4))

оптимальное V:
 [[0.95099005 0.96059601 0.970299   0.96059601]
 [0.96059601 0.         0.9801     0.        ]
 [0.970299   0.9801     0.99       0.        ]
 [0.         0.99       1.         0.        ]]
оптимальная политика:
 [[1 2 1 0]
 [1 0 1 0]
 [2 1 1 0]
 [0 2 2 0]]
